-- MySQL Script generated by MySQL Workbench
-- 01/30/16 19:29:41
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdcontroldeventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcontroldeventas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdcontroldeventas` ;

-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`persona` (
  `cod_persona` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`cliente` (
  `cod_cliente` INT(11) NOT NULL,
  `rut_cliente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_cliente`),
  CONSTRAINT `cliente_personaFK`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `bdcontroldeventas`.`persona` (`cod_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`proveedor` (
  `cod_proveedor` INT(11) NOT NULL,
  `rut_proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_proveedor`),
  CONSTRAINT `cod_proveedor`
    FOREIGN KEY (`cod_proveedor`)
    REFERENCES `bdcontroldeventas`.`persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`compra` (
  `cod_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_compra` DATE NOT NULL,
  `total_compra` BIGINT(20) NOT NULL,
  `cod_proveedorFK` INT(11) NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_compra`),
  INDEX `cod_proveedorFK_idx` (`cod_proveedorFK` ASC),
  CONSTRAINT `cod_proveedorFK`
    FOREIGN KEY (`cod_proveedorFK`)
    REFERENCES `bdcontroldeventas`.`proveedor` (`cod_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`producto` (
  `cod_producto` BIGINT(20) NOT NULL,
  `nombre_producto` VARCHAR(255) NOT NULL,
  `descripcion_producto` VARCHAR(255) NULL DEFAULT NULL,
  `unidad_producto` VARCHAR(20) NOT NULL,
  `precio_producto` BIGINT(20) NOT NULL,
  `precio_compra` BIGINT(20) NOT NULL,
  `stock_producto` INT(11) NOT NULL,
  PRIMARY KEY (`cod_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`detalle_compra` (
  `cod_detalle_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad_detalle_compra` INT(11) NOT NULL,
  `cod_productoFK` BIGINT(20) NOT NULL,
  `precio_producto` BIGINT(20) NOT NULL,
  `cod_compraFK` INT(11) NOT NULL,
  `subTotal` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cod_detalle_compra`, `cod_compraFK`),
  INDEX `cod_productoFK_idx` (`cod_productoFK` ASC),
  INDEX `cod_compraFK_idx` (`cod_compraFK` ASC),
  CONSTRAINT `cod_compraFK`
    FOREIGN KEY (`cod_compraFK`)
    REFERENCES `bdcontroldeventas`.`compra` (`cod_compra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_productoFK`
    FOREIGN KEY (`cod_productoFK`)
    REFERENCES `bdcontroldeventas`.`producto` (`cod_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`usuario` (
  `cod_usuario` INT(11) NOT NULL,
  `rut_usuario` VARCHAR(20) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(8) NOT NULL,
  `acceso` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  CONSTRAINT `usuario_personaFK`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `bdcontroldeventas`.`persona` (`cod_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`venta` (
  `cod_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `total_venta` BIGINT(20) NOT NULL,
  `cod_usuarioFK` INT(11) NOT NULL,
  `cod_clienteFK` INT(11) NOT NULL,
  `tipo_comprobante` VARCHAR(10) NOT NULL,
  `num_factura` BIGINT(20) NULL DEFAULT NULL,
  `pago` BIGINT(20) NOT NULL,
  `descuento` INT(11) NOT NULL,
  PRIMARY KEY (`cod_venta`),
  INDEX `venta_usuarioFK_idx` (`cod_usuarioFK` ASC),
  INDEX `venta_clienteFK_idx` (`cod_clienteFK` ASC),
  CONSTRAINT `venta_clienteFK`
    FOREIGN KEY (`cod_clienteFK`)
    REFERENCES `bdcontroldeventas`.`cliente` (`cod_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `venta_usuarioFK`
    FOREIGN KEY (`cod_usuarioFK`)
    REFERENCES `bdcontroldeventas`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontroldeventas`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontroldeventas`.`detalle_venta` (
  `cod_detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad_detalle` INT(11) NOT NULL,
  `cod_productoFK` BIGINT(20) NOT NULL,
  `precio_producto` BIGINT(20) NOT NULL,
  `cod_ventaFK` INT(11) NOT NULL,
  `subtotal` BIGINT(20) NOT NULL,
  `subPrecioCompra` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cod_detalle`, `cod_ventaFK`),
  INDEX `detalle_productoFK_idx` (`cod_productoFK` ASC),
  INDEX `detalle_ventaFK_idx` (`cod_ventaFK` ASC),
  CONSTRAINT `detalle_productoFK`
    FOREIGN KEY (`cod_productoFK`)
    REFERENCES `bdcontroldeventas`.`producto` (`cod_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detalle_ventaFK`
    FOREIGN KEY (`cod_ventaFK`)
    REFERENCES `bdcontroldeventas`.`venta` (`cod_venta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
